### PR TITLE
update supported distros

### PR DESCRIPTION
**Pull request by ShalokShalom**
Parrot is not listed on nspawn.org, so I removed it 

Added Garuda and NixOS

Not sure if nixos spelling is correct
Maybe with a hyphen?

### CODE REVIEW

**Comment by Edu4rdSHL** [comment]
Hello, thanks. I think that it's better to put something like "check nspawn -l" to avoid updating the script every time that a new distro is added.

**Comment by ShalokShalom** [comment]
That is out of the scope of what I trust myself to do

**Comment by vaporup** [comment]
I guess Edu4rdSHL meant you should just replace the text

```
One out of (archlinux,blackarch,centos,debian,fedora,kali,opensuse,garuda,nixos,ubuntu). Run $program -l/--list for more information.
```

with

```
Check $program -l/--list for more information and which distribution names to use.
```

**Comment by ShalokShalom** [comment]
done

**Comment by Edu4rdSHL** [comment]
Thank you!

**Pull request merged**
